name: 游 Solicitud de Funcionalidad
description: Proponer una nueva funcionalidad o mejora
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo de completar este formulario de solicitud de funcionalidad.

  - type: textarea
    id: problem
    attributes:
      label: Descripci칩n del Problema
      description: 쯈u칠 problema est치 resolviendo esta funcionalidad?
      placeholder: Describe el problema que te gustar칤a resolver...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Soluci칩n Propuesta
      description: 쮺칩mo te gustar칤a que se resolviera este problema?
      placeholder: Describe la soluci칩n que propones...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Criterios de 칄xito
      description: 쮺칩mo sabremos que esta funcionalidad est치 completa y funciona correctamente?
      placeholder: |
        - [ ] Criterio 1...
        - [ ] Criterio 2...
        - [ ] Criterio 3...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: 쮿as considerado alguna soluci칩n alternativa?
      placeholder: Describe cualquier alternativa que hayas considerado...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Contexto Adicional
      description: 쮿ay alg칰n contexto adicional o capturas de pantalla que ayuden a entender mejor la solicitud?
      placeholder: Agrega cualquier otro contexto, capturas de pantalla, mockups, etc.
    validations:
      required: false
